# Generated by Django 6.0.2 on 2026-02-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_role_user_is_verified_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
