# Generated by Django 6.0.2 on 2026-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_height_alter_customer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
