# Generated by Django 6.0.2 on 2026-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_age_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyCalories',
        ),
    ]
