# Generated by Django 6.0.2 on 2026-02-17 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailyentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='description',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='calorie_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='calories_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='core.customer'),
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='core.dailyentry')),
            ],
        ),
    ]
